In [218]:
import numpy as np
import pandas as pd
from sklearn.metrics import pairwise_distances_argmin

In [219]:
from sklearn.datasets import load_iris
iris = load_iris()
X = iris['data']
y = iris['target']

In [220]:
i=pd.DataFrame(iris.data,columns=iris.feature_names)
i['target'] = pd.Series(iris.target)

In [221]:
i

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [222]:
i.to_csv('iris.csv')

In [223]:
def myGeneratorfun(wsize=10):
    print("In myGeneratorfun:")
    counter=0  #counter to stop stream data after all data is used
    for chunk in pd.read_csv('iris.csv', chunksize=wsize):  #for loop to separate out data in chunks
        print("In for loop, counter vlaue is", counter)
        chunk_array=chunk.values  #Each chunk of data is equal to window size and convert it to array
        counter=counter+1  #increment counter by 1 know that one more chunk of data is used
        yield (chunk_array[:,:-1], chunk_array[:,-1])  #This yield statement returns chunk of data 
        if counter >= 15:  #the for loop will continue to send chunks of data till the if statement is not satisfied
            break  #after all the data is used as chunks

In [224]:
def find_clusters(X, no_of_clusters, rseed=2):
    
    #assigning initial random values to cluster centers
    val = np.random.RandomState(rseed)
    i = val.permutation(X.shape[0])[:no_of_clusters]
    centers = X[i]
    
    while True:
       
        #getting minimum distance of all data points with their corresponding cluster centers and fetching the clusters
        centroid_label = pairwise_distances_argmin(X, centers)
        
        #finding new centers by taking the mean of all data present in the respective clusters
        new_centers = np.array([X[centroid_label == i].mean(0)
                                for i in range(no_of_clusters)])
        
        #defining condition for convergence
        if np.all(centers == new_centers):
            break
        centers = new_centers
    
    return centers, centroid_label

In [243]:
myGenerator = myGeneratorfun(10)
i=0
temp = np.empty((0))
step2 = np.empty((0))
print(temp)
for (X,y) in myGenerator:
    print(i)
    print(X.shape)
    if i>2:
        '''
        [centers, centroid_label] = find_clusters(temp,3,2)
        step2 = np.append(step2,centers)
        temp = np.empty((0))
        i = 0
        [centers, centroid_label] = find_clusters(X,3,2)
        temp = np.append(temp,centers)
        i=i+1
        '''
        temp=temp.reshape(9,5)
        [centers, centroid_label] = find_clusters(temp,3,2)
        step2 = np.append(step2,centers)
        print(temp)
        temp=np.empty((0))
        [centers, centroid_label] = find_clusters(X,3,2)
        temp = np.append(temp,centers)
        i=0
        i=i+1
    else:
        [centers, centroid_label] = find_clusters(X,3,2)
        temp = np.append(temp,centers)
        i = i+1

[]
In myGeneratorfun:
In for loop, counter vlaue is 0
0
(10, 5)
In for loop, counter vlaue is 1
1
(10, 5)
In for loop, counter vlaue is 2
2
(10, 5)
In for loop, counter vlaue is 3
3
(10, 5)
[[ 4.          5.          3.53333333  1.53333333  0.26666667]
 [ 1.          4.9         3.23333333  1.36666667  0.2       ]
 [ 7.5         4.725       3.2         1.45        0.2       ]
 [14.          5.26666667  3.8         1.26666667  0.23333333]
 [11.          5.          3.36666667  1.5         0.16666667]
 [17.5         5.325       3.75        1.475       0.325     ]
 [24.          4.96666667  3.23333333  1.73333333  0.3       ]
 [21.          5.03333333  3.56666667  1.4         0.26666667]
 [27.5         5.025       3.375       1.525       0.25      ]]
In for loop, counter vlaue is 4
1
(10, 5)
In for loop, counter vlaue is 5
2
(10, 5)
In for loop, counter vlaue is 6
3
(10, 5)
[[34.          5.13333333  3.5         1.36666667  0.2       ]
 [31.          5.13333333  3.53333333  1.53333333  0.

In [234]:
centers.shape

(3, 5)

In [246]:
step2=step2.reshape(12,5)

In [247]:
step2

array([[ 14.16666667,   5.19722222,   3.63888889,   1.41388889,
          0.24166667],
       [  4.16666667,   4.875     ,   3.32222222,   1.45      ,
          0.22222222],
       [ 24.16666667,   5.00833333,   3.39166667,   1.55277778,
          0.27222222],
       [ 42.5       ,   4.89375   ,   3.32708333,   1.44583333,
          0.26875   ],
       [ 32.5       ,   5.13333333,   3.51666667,   1.45      ,
          0.21666667],
       [ 54.16666667,   6.13888889,   2.875     ,   4.39722222,
          1.38611111],
       [ 74.16666667,   6.25555556,   2.85277778,   4.49444444,
          1.41111111],
       [ 64.16666667,   5.85555556,   2.65555556,   4.12777778,
          1.26944444],
       [ 84.16666667,   5.80833333,   2.75277778,   4.26666667,
          1.33888889],
       [101.        ,   6.13333333,   2.875     ,   5.06388889,
          1.78888889],
       [ 92.5       ,   5.61666667,   2.7       ,   4.11666667,
          1.21666667],
       [112.625     ,   6.64375   ,   2.925

In [270]:
step3_1=np.empty((0))
step3_2=np.empty((0))
step3_1=np.append(step3_1,step2[0:6])
step3_2=np.append(step3_2,step2[6:12])

In [271]:
step3_1

array([14.16666667,  5.19722222,  3.63888889,  1.41388889,  0.24166667,
        4.16666667,  4.875     ,  3.32222222,  1.45      ,  0.22222222,
       24.16666667,  5.00833333,  3.39166667,  1.55277778,  0.27222222,
       42.5       ,  4.89375   ,  3.32708333,  1.44583333,  0.26875   ,
       32.5       ,  5.13333333,  3.51666667,  1.45      ,  0.21666667,
       54.16666667,  6.13888889,  2.875     ,  4.39722222,  1.38611111])

In [276]:
step3_1=step3_1.reshape(6,5)

In [273]:
step3_2

array([ 74.16666667,   6.25555556,   2.85277778,   4.49444444,
         1.41111111,  64.16666667,   5.85555556,   2.65555556,
         4.12777778,   1.26944444,  84.16666667,   5.80833333,
         2.75277778,   4.26666667,   1.33888889, 101.        ,
         6.13333333,   2.875     ,   5.06388889,   1.78888889,
        92.5       ,   5.61666667,   2.7       ,   4.11666667,
         1.21666667, 112.625     ,   6.64375   ,   2.925     ,
         5.63125   ,   2.05416667])

In [277]:
step3_2=step3_2.reshape(6,5)

In [278]:
step4=np.empty((0))
[centers,centroid_lable]=find_clusters(step3_1,3,2)
step4=np.append(step4,centers)
[centers,centroid_lable]=find_clusters(step3_2,3,2)
step4=np.append(step4,centers)

In [279]:
step4

array([ 28.33333333,   5.07083333,   3.45416667,   1.50138889,
         0.24444444,   9.16666667,   5.03611111,   3.48055556,
         1.43194444,   0.23194444,  48.33333333,   5.51631944,
         3.10104167,   2.92152778,   0.82743056,  88.33333333,
         5.7125    ,   2.72638889,   4.19166667,   1.27777778,
        69.16666667,   6.05555556,   2.75416667,   4.31111111,
         1.34027778, 106.8125    ,   6.38854167,   2.9       ,
         5.34756944,   1.92152778])

In [280]:
step4=step4.reshape(6,5)

In [281]:
step4

array([[ 28.33333333,   5.07083333,   3.45416667,   1.50138889,
          0.24444444],
       [  9.16666667,   5.03611111,   3.48055556,   1.43194444,
          0.23194444],
       [ 48.33333333,   5.51631944,   3.10104167,   2.92152778,
          0.82743056],
       [ 88.33333333,   5.7125    ,   2.72638889,   4.19166667,
          1.27777778],
       [ 69.16666667,   6.05555556,   2.75416667,   4.31111111,
          1.34027778],
       [106.8125    ,   6.38854167,   2.9       ,   5.34756944,
          1.92152778]])

In [282]:
[centers,centroid_label] = find_clusters(step4,3,2)

In [283]:
centers

array([[58.75      ,  5.7859375 ,  2.92760417,  3.61631944,  1.08385417],
       [18.75      ,  5.05347222,  3.46736111,  1.46666667,  0.23819444],
       [97.57291667,  6.05052083,  2.81319444,  4.76961806,  1.59965278]])

In [284]:
centroid_label

array([1, 1, 0, 2, 0, 2], dtype=int64)